// LUMORA Restaurant Complete Menu Catalog
// Each dish has its own individual photograph, category, description, and pricing.

const DEFAULT_MENU_ITEMS = [
  // ===================== BIRYANI =====================
  {
    _id: 'menu_biryani_01',
    name: 'Royal Chicken Dum Biryani',
    category: 'Biryani',
    price: 320,
    image: '/images/food/chicken-biryani.jpg',
    emoji: '🍚',
    rating: 4.9,
    reviewsCount: 380,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Slow-cooked fragrant long basmati rice layered with tender saffron spiced chicken, caramelized onions and fresh mint.',
    addOns: [{ name: 'Extra Raita', price: 25 }, { name: 'Boiled Egg', price: 20 }, { name: 'Mirchi Ka Salan', price: 30 }],
    prepTime: 25,
    stock: 50,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_biryani_02',
    name: 'Special Mutton Dum Biryani',
    category: 'Biryani',
    price: 420,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    emoji: '🍚',
    rating: 4.9,
    reviewsCount: 290,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Royal Hyderabadi mutton dum biryani with juicy bone-in cuts, rich aromatic spices and saffron infusion.',
    addOns: [{ name: 'Extra Raita', price: 25 }, { name: 'Extra Gravy', price: 35 }],
    prepTime: 30,
    stock: 40,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_biryani_03',
    name: 'Classic Beef Biryani',
    category: 'Biryani',
    price: 360,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    emoji: '🍚',
    rating: 4.8,
    reviewsCount: 215,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Succulent spiced beef chunks simmered with basmati rice, roasted whole spices and fried cashews.',
    addOns: [{ name: 'Extra Raita', price: 25 }, { name: 'Boiled Egg', price: 20 }],
    prepTime: 25,
    stock: 35,
    isAvailable: true,
  },
  {
    _id: 'menu_biryani_04',
    name: 'Spiced Egg Biryani',
    category: 'Biryani',
    price: 240,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80',
    emoji: '🥚',
    rating: 4.7,
    reviewsCount: 165,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Pan-roasted spiced hard-boiled eggs nested in aromatic dum-cooked basmati rice with fried onions.',
    addOns: [{ name: 'Extra Egg', price: 20 }, { name: 'Raita', price: 25 }],
    prepTime: 18,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_biryani_05',
    name: 'Royal Vegetable Dum Biryani',
    category: 'Biryani',
    price: 250,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    emoji: '🥦',
    rating: 4.8,
    reviewsCount: 195,
    dietary: ['veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Garden fresh florets, carrots, french beans and paneer layered with saffron basmati rice and rose water.',
    addOns: [{ name: 'Extra Paneer Cubes', price: 40 }, { name: 'Cucumber Raita', price: 25 }],
    prepTime: 20,
    stock: 40,
    isAvailable: true,
  },
  {
    _id: 'menu_biryani_06',
    name: 'Hyderabadi Chicken Dum Biryani',
    category: 'Biryani',
    price: 340,
    image: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=600&q=80',
    emoji: '🍚',
    rating: 4.9,
    reviewsCount: 310,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Authentic Nizam-style kacchi dum biryani marinated overnight with green chilies, yogurt, mint and kewra.',
    addOns: [{ name: 'Mirchi Ka Salan', price: 30 }, { name: 'Burani Raita', price: 30 }],
    prepTime: 25,
    stock: 50,
    isAvailable: true,
  },

  // ===================== PIZZA =====================
  {
    _id: 'menu_pizza_01',
    name: 'Artisan Margherita Pizza',
    category: 'Pizza',
    price: 340,
    image: '/images/food/pizza.jpg',
    emoji: '🍕',
    rating: 4.8,
    reviewsCount: 210,
    dietary: ['veg'],
    description: 'Hand-stretched sourdough crust topped with San Marzano tomato sauce, fresh creamy buffalo mozzarella, extra virgin olive oil and basil.',
    addOns: [{ name: 'Extra Cheese', price: 50 }, { name: 'Jalapenos & Olives', price: 35 }],
    prepTime: 18,
    stock: 50,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_pizza_02',
    name: 'Smoky BBQ Chicken Pizza',
    category: 'Pizza',
    price: 410,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    emoji: '🍕',
    rating: 4.9,
    reviewsCount: 245,
    dietary: ['non-veg'],
    description: 'Stone-baked pizza with hickory smoked chicken, roasted red onions, cilantro, and melting Monterey Jack cheese.',
    addOns: [{ name: 'Extra Cheese', price: 50 }, { name: 'Crispy Bacon Crumbs', price: 60 }],
    prepTime: 20,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_pizza_03',
    name: 'Classic Chicken Pizza',
    category: 'Pizza',
    price: 390,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
    emoji: '🍕',
    rating: 4.8,
    reviewsCount: 180,
    dietary: ['non-veg'],
    description: 'Seasoned herb chicken breast, sweet red bell peppers, charred sweetcorn and stretchy mozzarella on tomato base.',
    addOns: [{ name: 'Extra Cheese', price: 50 }, { name: 'Mushrooms', price: 35 }],
    prepTime: 18,
    stock: 40,
    isAvailable: true,
  },
  {
    _id: 'menu_pizza_04',
    name: 'Four Cheese Gourmet Pizza',
    category: 'Pizza',
    price: 420,
    image: 'https://images.unsplash.com/photo-1573821663912-569905455b1a?auto=format&fit=crop&w=600&q=80',
    emoji: '🧀',
    rating: 4.9,
    reviewsCount: 205,
    dietary: ['veg'],
    description: 'A decadent blend of aged Parmesan, Gorgonzola blue, Ricotta dollops and whole milk mozzarella cheese.',
    addOns: [{ name: 'Hot Honey Drizzle', price: 40 }, { name: 'Truffle Oil', price: 60 }],
    prepTime: 18,
    stock: 35,
    isAvailable: true,
  },
  {
    _id: 'menu_pizza_05',
    name: 'Classic Pepperoni Pizza',
    category: 'Pizza',
    price: 440,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
    emoji: '🍕',
    rating: 4.9,
    reviewsCount: 320,
    dietary: ['non-veg'],
    description: 'Generously loaded with spicy Italian pork pepperoni cups, rich oregano tomato sauce and bubbling mozzarella.',
    addOns: [{ name: 'Extra Pepperoni', price: 70 }, { name: 'Jalapeno Peppers', price: 30 }],
    prepTime: 18,
    stock: 45,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_pizza_06',
    name: 'Farmhouse Veggie Pizza',
    category: 'Pizza',
    price: 350,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
    emoji: '🥦',
    rating: 4.7,
    reviewsCount: 160,
    dietary: ['veg'],
    description: 'Crunchy bell peppers, ripe cherry tomatoes, black Kalamata olives, red onions and diced button mushrooms.',
    addOns: [{ name: 'Extra Cheese', price: 50 }, { name: 'Paneer Cubes', price: 40 }],
    prepTime: 16,
    stock: 40,
    isAvailable: true,
  },
  {
    _id: 'menu_pizza_07',
    name: 'Creamy Truffle Mushroom Pizza',
    category: 'Pizza',
    price: 430,
    image: 'https://images.unsplash.com/photo-1594007654729-407edc4be657?auto=format&fit=crop&w=600&q=80',
    emoji: '🍄',
    rating: 4.9,
    reviewsCount: 175,
    dietary: ['veg'],
    description: 'Roasted portobello and cremini mushrooms, caramelized shallots, thyme, garlic cream base and black truffle oil.',
    addOns: [{ name: 'Shaved Parmesan', price: 45 }],
    prepTime: 19,
    stock: 30,
    isAvailable: true,
  },

  // ===================== PASTA =====================
  {
    _id: 'menu_pasta_01',
    name: 'Creamy Fettuccine Alfredo',
    category: 'Pasta',
    price: 330,
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=600&q=80',
    emoji: '🍝',
    rating: 4.8,
    reviewsCount: 185,
    dietary: ['veg'],
    description: 'Silky egg fettuccine tossed in rich European butter, crushed garlic, heavy cream and freshly grated Parmigiano Reggiano.',
    addOns: [{ name: 'Garlic Bread (2 pcs)', price: 45 }, { name: 'Extra Parmesan', price: 35 }],
    prepTime: 16,
    stock: 40,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_pasta_02',
    name: 'Grilled Chicken Penne Pasta',
    category: 'Pasta',
    price: 370,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281724?auto=format&fit=crop&w=600&q=80',
    emoji: '🍝',
    rating: 4.9,
    reviewsCount: 220,
    dietary: ['non-veg'],
    description: 'Al dente penne with tender herb-seared chicken strips in a luscious pink sun-dried tomato cream sauce.',
    addOns: [{ name: 'Extra Grilled Chicken', price: 60 }, { name: 'Cheesy Garlic Bread', price: 60 }],
    prepTime: 18,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_pasta_03',
    name: 'Spicy Penne Arrabbiata',
    category: 'Pasta',
    price: 290,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    emoji: '🌶️',
    rating: 4.7,
    reviewsCount: 155,
    dietary: ['veg', 'vegan'],
    hasSpiceLevel: true,
    description: 'Rustic Roman sauce with San Marzano plum tomatoes, fiery red chili flakes, roasted garlic and fresh Italian parsley.',
    addOns: [{ name: 'Black Olives & Capers', price: 35 }, { name: 'Fresh Burrata Cheese', price: 80 }],
    prepTime: 15,
    stock: 50,
    isAvailable: true,
  },
  {
    _id: 'menu_pasta_04',
    name: 'Classic Spaghetti Carbonara',
    category: 'Pasta',
    price: 380,
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=600&q=80',
    emoji: '🍝',
    rating: 4.9,
    reviewsCount: 195,
    dietary: ['non-veg'],
    description: 'Traditional spaghetti coated with rich egg yolk emulsion, crispy smoked pancetta bacon bits and freshly cracked black pepper.',
    addOns: [{ name: 'Extra Pancetta Crisp', price: 65 }],
    prepTime: 17,
    stock: 35,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_pasta_05',
    name: 'Creamy Garlic Mushroom Pasta',
    category: 'Pasta',
    price: 340,
    image: 'https://images.unsplash.com/photo-1556761223-4c4282c73f77?auto=format&fit=crop&w=600&q=80',
    emoji: '🍄',
    rating: 4.8,
    reviewsCount: 170,
    dietary: ['veg'],
    description: 'Tagliatelle ribbons tossed with browned butter wild button mushrooms, garlic confit, white wine reduction and cream.',
    addOns: [{ name: 'Truffle Oil Drizzle', price: 50 }, { name: 'Toasted Pine Nuts', price: 40 }],
    prepTime: 16,
    stock: 40,
    isAvailable: true,
  },

  // ===================== FRIED RICE =====================
  {
    _id: 'menu_rice_01',
    name: 'Golden Chicken Fried Rice',
    category: 'Fried Rice',
    price: 260,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    emoji: '🍚',
    rating: 4.8,
    reviewsCount: 270,
    dietary: ['non-veg'],
    description: 'Fluffy wok-fried jasmine rice tossed with diced chicken breast, scrambled egg ribbons, carrots and toasted sesame oil.',
    addOns: [{ name: 'Chili Chicken Side', price: 90 }, { name: 'Fried Egg on Top', price: 25 }],
    prepTime: 14,
    stock: 55,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_rice_02',
    name: 'Savory Beef Fried Rice',
    category: 'Fried Rice',
    price: 290,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80',
    emoji: '🍚',
    rating: 4.8,
    reviewsCount: 195,
    dietary: ['non-veg'],
    description: 'High-heat wok charred rice with thinly sliced tender marinated beef, scallions, garlic, and dark aged soy sauce.',
    addOns: [{ name: 'Extra Beef Slices', price: 75 }, { name: 'Spicy Kimchi', price: 40 }],
    prepTime: 15,
    stock: 40,
    isAvailable: true,
  },
  {
    _id: 'menu_rice_03',
    name: 'Fluffy Egg Fried Rice',
    category: 'Fried Rice',
    price: 210,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    emoji: '🥚',
    rating: 4.7,
    reviewsCount: 160,
    dietary: ['non-veg'],
    description: 'Classic Chinese street-style rice stir-fried with fragrant scallion butter, beaten farm eggs and cracked white pepper.',
    addOns: [{ name: 'Extra Egg', price: 20 }, { name: 'Crispy Garlic Topping', price: 15 }],
    prepTime: 12,
    stock: 50,
    isAvailable: true,
  },
  {
    _id: 'menu_rice_04',
    name: 'Garden Vegetable Fried Rice',
    category: 'Fried Rice',
    price: 190,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    emoji: '🥦',
    rating: 4.6,
    reviewsCount: 140,
    dietary: ['veg', 'vegan'],
    description: 'Crisp green beans, sweet peas, sweetcorn and baby corn flash-fried with fragrant long grain rice and spring onions.',
    addOns: [{ name: 'Veg Manchurian Gravy', price: 75 }, { name: 'Paneer Cubes', price: 35 }],
    prepTime: 12,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_rice_05',
    name: 'Fiery Schezwan Fried Rice',
    category: 'Fried Rice',
    price: 240,
    image: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=600&q=80',
    emoji: '🌶️',
    rating: 4.8,
    reviewsCount: 230,
    dietary: ['veg'],
    hasSpiceLevel: true,
    description: 'Spicy wok-tossed rice flavored with authentic Sichuan chili paste, crushed garlic, ginger and crunchy celery.',
    addOns: [{ name: 'Add Chicken', price: 50 }, { name: 'Fried Egg', price: 25 }],
    prepTime: 14,
    stock: 50,
    isAvailable: true,
  },

  // ===================== NOODLES =====================
  {
    _id: 'menu_noodles_01',
    name: 'Wok-Tossed Chicken Noodles',
    category: 'Noodles',
    price: 250,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    emoji: '🍜',
    rating: 4.8,
    reviewsCount: 265,
    dietary: ['non-veg'],
    description: 'Smoky wok tossed egg noodles with juicy shredded chicken, julienned bell peppers, shredded cabbage and light soy.',
    addOns: [{ name: 'Chili Chicken Side', price: 90 }, { name: 'Extra Chicken', price: 45 }],
    prepTime: 14,
    stock: 50,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_noodles_02',
    name: 'Savory Beef Noodles',
    category: 'Noodles',
    price: 280,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    emoji: '🍜',
    rating: 4.9,
    reviewsCount: 185,
    dietary: ['non-veg'],
    description: 'Thick wheat noodles tossed in savory hoisin beef reduction with tender marinated steak strips and bok choy.',
    addOns: [{ name: 'Crispy Fried Wontons', price: 45 }],
    prepTime: 16,
    stock: 35,
    isAvailable: true,
  },
  {
    _id: 'menu_noodles_03',
    name: 'Scrambled Egg Noodles',
    category: 'Noodles',
    price: 200,
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=600&q=80',
    emoji: '🍜',
    rating: 4.7,
    reviewsCount: 150,
    dietary: ['non-veg'],
    description: 'Fine wheat noodles stir-fried with fluffy scrambled eggs, bean sprouts, spring onions and toasted sesame seeds.',
    addOns: [{ name: 'Extra Egg', price: 20 }, { name: 'Chili Garlic Oil', price: 15 }],
    prepTime: 12,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_noodles_04',
    name: 'Hakka Vegetable Noodles',
    category: 'Noodles',
    price: 180,
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80',
    emoji: '🥦',
    rating: 4.6,
    reviewsCount: 175,
    dietary: ['veg', 'vegan'],
    description: 'Crisp shredded carrots, purple cabbage, capsicum and scallions wok tossed with springy hakka noodles.',
    addOns: [{ name: 'Veg Manchurian', price: 75 }],
    prepTime: 12,
    stock: 50,
    isAvailable: true,
  },
  {
    _id: 'menu_noodles_05',
    name: 'Spicy Schezwan Noodles',
    category: 'Noodles',
    price: 230,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80',
    emoji: '🌶️',
    rating: 4.8,
    reviewsCount: 220,
    dietary: ['veg'],
    hasSpiceLevel: true,
    description: 'Zesty red hot chili paste stir-fried with wheat noodles, roasted garlic, spring onions and crunchy vegetables.',
    addOns: [{ name: 'Add Chicken', price: 50 }, { name: 'Fried Egg', price: 25 }],
    prepTime: 14,
    stock: 45,
    isAvailable: true,
  },

  // ===================== SHAWARMA =====================
  {
    _id: 'menu_shawarma_01',
    name: 'Classic Chicken Shawarma',
    category: 'Shawarma',
    price: 160,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
    emoji: '🌯',
    rating: 4.9,
    reviewsCount: 340,
    dietary: ['non-veg'],
    description: 'Shaved Lebanese rotisserie chicken wrapped in warm rumali roti with creamy garlic toum sauce, french fries and pickled turnip.',
    addOns: [{ name: 'Extra Toum Garlic Sauce', price: 25 }, { name: 'Melted Cheese', price: 30 }],
    prepTime: 10,
    stock: 60,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_shawarma_02',
    name: 'Melted Cheese Shawarma',
    category: 'Shawarma',
    price: 190,
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=600&q=80',
    emoji: '🧀',
    rating: 4.8,
    reviewsCount: 270,
    dietary: ['non-veg'],
    description: 'Succulent spiced rotisserie chicken loaded with warm gooey melted mozzarella and cheddar cheese sauce.',
    addOns: [{ name: 'Jalapenos', price: 20 }, { name: 'Extra Meat', price: 40 }],
    prepTime: 12,
    stock: 50,
    isAvailable: true,
  },
  {
    _id: 'menu_shawarma_03',
    name: 'Fiery Spicy Shawarma',
    category: 'Shawarma',
    price: 180,
    image: 'https://images.unsplash.com/photo-1633321702518-7feccafb94d5?auto=format&fit=crop&w=600&q=80',
    emoji: '🌶️',
    rating: 4.8,
    reviewsCount: 215,
    dietary: ['non-veg'],
    hasSpiceLevel: true,
    description: 'Juicy spiced chicken basted in fiery peri-peri harissa paste, pickled jalapeños and spicy garlic emulsion.',
    addOns: [{ name: 'Extra Spicy Sauce', price: 20 }, { name: 'French Fries', price: 30 }],
    prepTime: 10,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_shawarma_04',
    name: 'Gourmet Plate Shawarma',
    category: 'Shawarma',
    price: 260,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    emoji: '🍽️',
    rating: 4.9,
    reviewsCount: 290,
    dietary: ['non-veg'],
    description: 'Generous platter of thinly sliced roasted chicken, creamy chickpea hummus, 2 toasted pita breads, spiced french fries and garlic toum.',
    addOns: [{ name: 'Extra Pita Bread', price: 25 }, { name: 'Hummus Cup', price: 40 }],
    prepTime: 15,
    stock: 40,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_shawarma_05',
    name: 'Authentic Arabic Shawarma',
    category: 'Shawarma',
    price: 210,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    emoji: '🌯',
    rating: 4.9,
    reviewsCount: 230,
    dietary: ['non-veg'],
    description: 'Traditional Middle Eastern toasted saj bread stuffed with spiced chicken, crisp potato sticks, dill pickles and authentic tahini dip.',
    addOns: [{ name: 'Tahini Dip', price: 25 }, { name: 'Pickled Veggie Cup', price: 20 }],
    prepTime: 12,
    stock: 45,
    isAvailable: true,
  },

  // ===================== FRIED CHICKEN =====================
  {
    _id: 'menu_friedchick_01',
    name: 'Golden Crispy Fried Chicken',
    category: 'Fried Chicken',
    price: 290,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
    emoji: '🍗',
    rating: 4.9,
    reviewsCount: 310,
    dietary: ['non-veg'],
    description: '4 pieces of buttermilk brined, golden crunchy coated bone-in chicken with our secret 11-spice herb seasoning. Served with garlic dip.',
    addOns: [{ name: 'Spicy Mayo Dip', price: 25 }, { name: 'Crispy French Fries', price: 50 }],
    prepTime: 16,
    stock: 50,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_friedchick_02',
    name: 'Honey Glazed Chicken Wings',
    category: 'Fried Chicken',
    price: 270,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80',
    emoji: '🍗',
    rating: 4.8,
    reviewsCount: 240,
    dietary: ['non-veg'],
    description: '6 crispy fried chicken wings tossed in rich organic wild honey, toasted sesame seeds, and mild smoked chili glaze.',
    addOns: [{ name: 'Ranch Dressing Dip', price: 30 }, { name: 'Celery Sticks', price: 20 }],
    prepTime: 15,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_friedchick_03',
    name: 'Tender Crispy Chicken Strips',
    category: 'Fried Chicken',
    price: 240,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
    emoji: '🍗',
    rating: 4.8,
    reviewsCount: 220,
    dietary: ['non-veg'],
    description: 'Juicy 100% chicken breast tenderloins fried to crunchy perfection. Served with honey mustard and smoky BBQ sauce.',
    addOns: [{ name: 'Cheddar Cheese Dip', price: 35 }, { name: 'Cajun Spice Rub', price: 15 }],
    prepTime: 12,
    stock: 50,
    isAvailable: true,
  },
  {
    _id: 'menu_friedchick_04',
    name: 'Crunchy Chicken Popcorn',
    category: 'Fried Chicken',
    price: 190,
    image: 'https://images.unsplash.com/photo-1585325701165-351af916e581?auto=format&fit=crop&w=600&q=80',
    emoji: '🍿',
    rating: 4.7,
    reviewsCount: 180,
    dietary: ['non-veg'],
    description: 'Bite-sized seasoned chicken nuggets in crunchy panko breading. The ultimate quick finger snack with tangy dips.',
    addOns: [{ name: 'Peri Peri Shake Seasoning', price: 20 }, { name: 'Cheese Sauce', price: 30 }],
    prepTime: 10,
    stock: 60,
    isAvailable: true,
  },
  {
    _id: 'menu_friedchick_05',
    name: 'Fiery Spicy Fried Chicken',
    category: 'Fried Chicken',
    price: 310,
    image: 'https://images.unsplash.com/photo-1625938145744-e380515399b7?auto=format&fit=crop&w=600&q=80',
    emoji: '🔥',
    rating: 4.9,
    reviewsCount: 260,
    dietary: ['non-veg'],
    hasSpiceLevel: true,
    description: 'Nashville-style hot chicken basted with cayenne chili oil, brown sugar butter and served over thick butter bread with dill pickles.',
    addOns: [{ name: 'Extra Hot Sauce Dip', price: 25 }, { name: 'Coleslaw Salad', price: 35 }],
    prepTime: 16,
    stock: 40,
    isAvailable: true,
  },

  // ===================== BURGER =====================
  {
    _id: 'menu_burger_01',
    name: 'Double Smash Gourmet Burger',
    category: 'Burger',
    price: 260,
    image: '/images/food/burger.jpg',
    emoji: '🍔',
    rating: 4.8,
    reviewsCount: 320,
    dietary: ['non-veg'],
    description: 'Flame-seared twin beef/chicken smash patties, aged cheddar cheese, crunchy dill pickles, crisp lettuce and secret truffle aioli on toasted brioche.',
    addOns: [{ name: 'Crispy Fries', price: 60 }, { name: 'Extra Patty', price: 80 }, { name: 'Caramelized Onions', price: 30 }],
    prepTime: 15,
    stock: 50,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_burger_02',
    name: 'Classic Prime Beef Burger',
    category: 'Burger',
    price: 280,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    emoji: '🍔',
    rating: 4.9,
    reviewsCount: 290,
    dietary: ['non-veg'],
    description: 'Thick grilled tenderloin beef patty, melted Wisconsin cheddar, ripe vine tomatoes, red onion rings and signature burger sauce.',
    addOns: [{ name: 'Bacon Rashers', price: 60 }, { name: 'Fried Egg', price: 25 }],
    prepTime: 16,
    stock: 40,
    isAvailable: true,
  },
  {
    _id: 'menu_burger_03',
    name: 'Crispy Chicken Crunch Burger',
    category: 'Burger',
    price: 240,
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=600&q=80',
    emoji: '🍔',
    rating: 4.8,
    reviewsCount: 250,
    dietary: ['non-veg'],
    description: 'Deep fried buttermilk spiced chicken breast fillet topped with creamy iceberg coleslaw and sweet chili garlic sauce.',
    addOns: [{ name: 'Cheese Slice', price: 30 }, { name: 'French Fries', price: 50 }],
    prepTime: 14,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_burger_04',
    name: 'Golden Veggie Crunch Burger',
    category: 'Burger',
    price: 210,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
    emoji: '🍔',
    rating: 4.7,
    reviewsCount: 180,
    dietary: ['veg'],
    description: 'Golden crumbed spiced vegetable patty with pickled gherkins, creamy chipotle slaw and melted cheddar cheese.',
    addOns: [{ name: 'Cheese Slice', price: 30 }, { name: 'Peri Peri Fries', price: 70 }],
    prepTime: 12,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_burger_05',
    name: 'Smoky BBQ Bacon Burger',
    category: 'Burger',
    price: 310,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
    emoji: '🍔',
    rating: 4.9,
    reviewsCount: 210,
    dietary: ['non-veg'],
    description: 'Charbroiled beef patty smothered in smoky Kansas BBQ glaze, crispy smoked bacon strips, beer-battered onion rings and sharp cheddar.',
    addOns: [{ name: 'Extra Onion Rings', price: 40 }],
    prepTime: 16,
    stock: 35,
    isAvailable: true,
  },

  // ===================== ALFAHAM =====================
  {
    _id: 'menu_alfaham_01',
    name: 'Arabian Charcoal Alfaham',
    category: 'Alfaham',
    price: 360,
    image: '/images/food/alfaham.jpg',
    emoji: '🔥',
    rating: 4.9,
    reviewsCount: 430,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Succulent half chicken marinated in Yemeni spices, slow-grilled over natural charcoal embers. Served with garlic toum, pickles, and hot pita.',
    addOns: [{ name: 'Garlic Toum Dip', price: 30 }, { name: 'Spicy Arabian Rice', price: 80 }, { name: 'Extra Pita Bread', price: 25 }],
    prepTime: 25,
    stock: 40,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_alfaham_02',
    name: 'Fiery Peri Peri Alfaham',
    category: 'Alfaham',
    price: 380,
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
    emoji: '🔥',
    rating: 4.9,
    reviewsCount: 340,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Char-grilled Alfaham chicken basted with vibrant African bird\'s eye chili glaze and fresh citrus herb butter.',
    addOns: [{ name: 'Garlic Toum Dip', price: 30 }, { name: 'Fresh Mint Chutney', price: 25 }],
    prepTime: 25,
    stock: 40,
    isAvailable: true,
  },
  {
    _id: 'menu_alfaham_03',
    name: 'Honey Pepper Glazed Alfaham',
    category: 'Alfaham',
    price: 390,
    image: 'https://images.unsplash.com/photo-1527477378408-1bc0605915d0?auto=format&fit=crop&w=600&q=80',
    emoji: '🍯',
    rating: 4.8,
    reviewsCount: 220,
    dietary: ['non-veg', 'gluten-free'],
    description: 'Slow charcoal roasted chicken kissed with pure highland honey, coarse crushed Malabar black pepper and lemon zest.',
    addOns: [{ name: 'Spicy Fries', price: 50 }, { name: 'Garlic Toum', price: 30 }],
    prepTime: 24,
    stock: 35,
    isAvailable: true,
  },
  {
    _id: 'menu_alfaham_04',
    name: 'Green Chilli Kanthari Alfaham',
    category: 'Alfaham',
    price: 380,
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=600&q=80',
    emoji: '🌶️',
    rating: 4.9,
    reviewsCount: 280,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Marinated in bird’s eye green chillies, shallots, curry leaves, and freshly squeezed coconut oil before smoke grilling.',
    addOns: [{ name: 'Malabar Porotta (2 pcs)', price: 40 }, { name: 'Mayonnaise Cup', price: 25 }],
    prepTime: 25,
    stock: 35,
    isAvailable: true,
  },

  // ===================== STARTERS =====================
  {
    _id: 'menu_starter_01',
    name: 'Crispy Starters Tasting Platter',
    category: 'Starters',
    price: 290,
    image: '/images/food/starters.jpg',
    emoji: '🍢',
    rating: 4.8,
    reviewsCount: 220,
    dietary: ['veg'],
    description: 'Grand tasting board with golden spring rolls, charred cottage cheese paneer tikka skewers, crunchy bites and three signature dipping sauces.',
    addOns: [{ name: 'Extra Mint Chutney', price: 20 }, { name: 'Sweet Chili Dip', price: 20 }],
    prepTime: 16,
    stock: 40,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_starter_02',
    name: 'Paneer Tikka Angara',
    category: 'Starters',
    price: 260,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    emoji: '🍢',
    rating: 4.8,
    reviewsCount: 250,
    dietary: ['veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Clay oven charred fresh cottage cheese marinated in Kashmiri chili, hung curd, and roasted cumin seeds.',
    addOns: [{ name: 'Mint Chutney', price: 15 }, { name: 'Butter Naan', price: 35 }],
    prepTime: 15,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_starter_03',
    name: 'Charred Chicken Tikka Skewers',
    category: 'Starters',
    price: 310,
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
    emoji: '🍢',
    rating: 4.9,
    reviewsCount: 295,
    dietary: ['non-veg', 'gluten-free'],
    hasSpiceLevel: true,
    description: 'Juicy boneless chicken thighs steeped in spiced yogurt, smoked mustard oil and fenugreek, roasted in intense tandoor heat.',
    addOns: [{ name: 'Pickled Onion Salad', price: 20 }, { name: 'Mint Dip', price: 20 }],
    prepTime: 16,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_starter_04',
    name: 'Crispy Vegetable Spring Rolls',
    category: 'Starters',
    price: 190,
    image: 'https://images.unsplash.com/photo-1548946526-f69e2424cf45?auto=format&fit=crop&w=600&q=80',
    emoji: '🥟',
    rating: 4.7,
    reviewsCount: 170,
    dietary: ['veg', 'vegan'],
    description: 'Golden pastry skins filled with seasoned shredded carrots, cabbage, glass noodles and wood ear mushrooms with sweet chili dip.',
    addOns: [{ name: 'Sweet Chili Sauce', price: 20 }],
    prepTime: 12,
    stock: 50,
    isAvailable: true,
  },

  // ===================== DESSERTS =====================
  {
    _id: 'menu_dessert_01',
    name: 'Warm Molten Chocolate Lava Cake',
    category: 'Desserts',
    price: 170,
    image: '/images/food/desserts.jpg',
    emoji: '🍫',
    rating: 4.9,
    reviewsCount: 310,
    dietary: ['veg'],
    description: 'Decadent baked Belgian chocolate cake with oozing warm molten center, accompanied by vanilla bean ice cream scoop and fresh berries.',
    addOns: [{ name: 'Extra Ice Cream Scoop', price: 40 }],
    prepTime: 8,
    stock: 40,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_dessert_02',
    name: 'Shahi Royal Gulab Jamun',
    category: 'Desserts',
    price: 120,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    emoji: '🍡',
    rating: 4.8,
    reviewsCount: 190,
    dietary: ['veg'],
    description: 'Warm milk dumplings soaked in cardamom saffron syrup, topped with edible silver leaf and sliced pistachios.',
    prepTime: 5,
    stock: 50,
    isAvailable: true,
  },
  {
    _id: 'menu_dessert_03',
    name: 'Rich Fudgy Chocolate Brownie',
    category: 'Desserts',
    price: 160,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    emoji: '🍫',
    rating: 4.9,
    reviewsCount: 230,
    dietary: ['veg'],
    description: 'Dense dark chocolate walnut brownie served warm with melted fudge chocolate sauce drizzle and whipped cream.',
    addOns: [{ name: 'Vanilla Ice Cream Scoop', price: 40 }],
    prepTime: 6,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_dessert_04',
    name: 'Classic New York Cheesecake',
    category: 'Desserts',
    price: 195,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
    emoji: '🍰',
    rating: 4.9,
    reviewsCount: 260,
    dietary: ['veg'],
    description: 'Velvety Philadelphia cream cheese filling on buttery graham cracker crust, topped with raspberry coulis.',
    prepTime: 5,
    stock: 35,
    isAvailable: true,
  },

  // ===================== ICE CREAM =====================
  {
    _id: 'menu_icecream_01',
    name: 'Vanilla Ice Cream',
    category: 'Ice Cream',
    price: 110,
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=600&q=80',
    emoji: '🍨',
    rating: 4.8,
    reviewsCount: 190,
    dietary: ['veg', 'gluten-free'],
    description: 'Double churned classic Madagascar bourbon vanilla bean ice cream with pure sweet dairy cream.',
    addOns: [{ name: 'Chocolate Sauce', price: 20 }, { name: 'Waffle Cone', price: 25 }],
    prepTime: 4,
    stock: 60,
    isAvailable: true,
  },
  {
    _id: 'menu_icecream_02',
    name: 'Chocolate Ice Cream',
    category: 'Ice Cream',
    price: 130,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    emoji: '🍨',
    rating: 4.9,
    reviewsCount: 280,
    dietary: ['veg', 'gluten-free'],
    description: 'Rich bittersweet Dutch cocoa ice cream folded with dark chocolate curls and roasted hazelnut bits.',
    addOns: [{ name: 'Choco Chips', price: 20 }, { name: 'Chocolate Fudge', price: 25 }],
    prepTime: 4,
    stock: 60,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_icecream_03',
    name: 'Strawberry Ice Cream',
    category: 'Ice Cream',
    price: 120,
    image: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=600&q=80',
    emoji: '🍓',
    rating: 4.8,
    reviewsCount: 175,
    dietary: ['veg', 'gluten-free'],
    description: 'Creamy blush ice cream infused with ripe crushed Mahabaleshwar strawberries and wild strawberry ribbon.',
    addOns: [{ name: 'Fresh Berries', price: 30 }, { name: 'Waffle Cone', price: 25 }],
    prepTime: 4,
    stock: 50,
    isAvailable: true,
  },
  {
    _id: 'menu_icecream_04',
    name: 'Mango Ice Cream',
    category: 'Ice Cream',
    price: 130,
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=600&q=80',
    emoji: '🥭',
    rating: 4.9,
    reviewsCount: 240,
    dietary: ['veg', 'gluten-free'],
    description: 'Sun-ripened Ratnagiri Alphonso mango puree churned into luscious tropical golden gelato.',
    addOns: [{ name: 'Mango Pulp Glaze', price: 25 }],
    prepTime: 4,
    stock: 50,
    isAvailable: true,
  },
  {
    _id: 'menu_icecream_05',
    name: 'Pista Ice Cream',
    category: 'Ice Cream',
    price: 140,
    image: 'https://images.unsplash.com/photo-1580915411954-282cb1b0d780?auto=format&fit=crop&w=600&q=80',
    emoji: '🍨',
    rating: 4.8,
    reviewsCount: 160,
    dietary: ['veg', 'gluten-free'],
    description: 'Traditional Persian style pistachio gelato enriched with roasted green pistachio chunks and cardamom hint.',
    addOns: [{ name: 'Crushed Dry Fruits', price: 30 }],
    prepTime: 4,
    stock: 45,
    isAvailable: true,
  },
  {
    _id: 'menu_icecream_06',
    name: 'Butterscotch Ice Cream',
    category: 'Ice Cream',
    price: 130,
    image: 'https://images.unsplash.com/photo-1549395156-e0c1fe6fc7a5?auto=format&fit=crop&w=600&q=80',
    emoji: '🍨',
    rating: 4.8,
    reviewsCount: 195,
    dietary: ['veg', 'gluten-free'],
    description: 'Velvety cream ice cream swirled with golden caramel toffee ribbons and crunchy cashew praline.',
    addOns: [{ name: 'Praline Crunch', price: 25 }],
    prepTime: 4,
    stock: 50,
    isAvailable: true,
  },

  // ===================== DRINKS =====================
  {
    _id: 'menu_drink_01',
    name: 'Sparkling Mint Lime Mojito',
    category: 'Drinks',
    price: 120,
    image: '/images/food/drinks.jpg',
    emoji: '🍹',
    rating: 4.8,
    reviewsCount: 195,
    dietary: ['veg', 'vegan', 'gluten-free'],
    description: 'Ultra refreshing sparkling mocktail with crushed garden mint leaves, freshly squeezed Tahitian limes, cane syrup and soda.',
    prepTime: 4,
    stock: 70,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_drink_02',
    name: 'Strawberry Mojito',
    category: 'Drinks',
    price: 140,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    emoji: '🍓',
    rating: 4.9,
    reviewsCount: 180,
    dietary: ['veg', 'vegan', 'gluten-free'],
    description: 'Muddled fresh strawberries, mint sprigs, lime wedges, strawberry cordial topped with fizzy club soda.',
    prepTime: 4,
    stock: 60,
    isAvailable: true,
  },
  {
    _id: 'menu_drink_03',
    name: 'Green Apple Mojito',
    category: 'Drinks',
    price: 140,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    emoji: '🍏',
    rating: 4.8,
    reviewsCount: 160,
    dietary: ['veg', 'vegan', 'gluten-free'],
    description: 'Crisp green Granny Smith apple syrup, fresh garden mint, zesty lime juice and sparkling mineral water.',
    prepTime: 4,
    stock: 60,
    isAvailable: true,
  },
  {
    _id: 'menu_drink_04',
    name: 'Classic Virgin Mojito',
    category: 'Drinks',
    price: 110,
    image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=600&q=80',
    emoji: '🍋',
    rating: 4.7,
    reviewsCount: 150,
    dietary: ['veg', 'vegan', 'gluten-free'],
    description: 'Crisp, citrusy and ice-cold mocktail with freshly muddled lime halves, crushed ice, mint and sparkling soda.',
    prepTime: 4,
    stock: 70,
    isAvailable: true,
  },
  {
    _id: 'menu_drink_05',
    name: 'Royal Mango Thick Lassi',
    category: 'Drinks',
    price: 110,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    emoji: '🥭',
    rating: 4.8,
    reviewsCount: 210,
    dietary: ['veg', 'gluten-free'],
    description: 'Rich blended yoghurt smoothie made with Alphonso mango pulp, saffron strands, and crushed pistachios.',
    prepTime: 5,
    stock: 65,
    isAvailable: true,
  },
  {
    _id: 'menu_drink_06',
    name: 'Creamy Chocolate Milkshake',
    category: 'Drinks',
    price: 150,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
    emoji: '🍫',
    rating: 4.9,
    reviewsCount: 260,
    dietary: ['veg'],
    description: 'Thick hand-spun milkshake blended with Belgian chocolate gelato, whole milk, chocolate fudge and whipped cream.',
    prepTime: 5,
    stock: 55,
    isAvailable: true,
    isSpecial: true,
  },
  {
    _id: 'menu_drink_07',
    name: 'Chilled Iced Cold Coffee',
    category: 'Drinks',
    price: 130,
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    emoji: '☕',
    rating: 4.8,
    reviewsCount: 220,
    dietary: ['veg', 'gluten-free'],
    description: 'Freshly pulled dark roast espresso shaken over ice with condensed milk and a dollop of vanilla cream.',
    prepTime: 4,
    stock: 65,
    isAvailable: true,
  },
  {
    _id: 'menu_drink_08',
    name: 'Fizzy Fresh Lime Soda',
    category: 'Drinks',
    price: 70,
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=600&q=80',
    emoji: '🍋',
    rating: 4.7,
    reviewsCount: 140,
    dietary: ['veg', 'vegan', 'gluten-free'],
    description: 'Classic sweet and salted freshly squeezed lime juice with chilled sparkling soda.',
    prepTime: 3,
    stock: 80,
    isAvailable: true,
  },
];

module.exports = DEFAULT_MENU_ITEMS;
